services:
  db:
    image: postgis/postgis:15-3.3
    platform: linux/amd64
    environment:
      POSTGRES_DB: addr_district_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: addr_district_db
      DB_USER: postgres
      DB_PASSWORD: password
      GEOMANCER_BASE_URL: https://tools.wprdc.org/geo
      CENSUS_GEOCODER_URL: https://geocoding.geo.census.gov/geocoder
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: